[package]
name = "couchbase-lite-core-sys"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
crate-type=["rlib", "staticlib"]

[build-dependencies]
cmake = "0.1.42"
bindgen = "0.52.0"
cc = "1.0.48"

[features]
static = []
