[package]
name = "couchbase-lite"
version = "0.1.0"
authors = ["Evgeniy A. Dushistov <dushistov@mail.ru>"]
edition = "2018"

[lib]
crate-type=["rlib", "staticlib"]

[dependencies]
couchbase-lite-core-sys = { path = "../couchbase-lite-core-sys" }
serde = { version = "1.0.104", features = ["derive"] }
uuid = { version = "0.8.1", features = ["v4", "serde", "v3"] }
serde_json = "1.0.44"
json5 = "0.2.5"
fallible-streaming-iterator = "0.1.9"
bitflags = "1.2.1"
once_cell = "1.2.0"
log = "0.4.8"

[dev-dependencies]
tempfile = "3.0"
env_logger = "0.7"

[features]
sys-static = ["couchbase-lite-core-sys/static"]